### ISSUE TITLE
[SOLVED] Browser-sync

### ISSUE THREAD

**Issue by MMrj9** [goldfire/phaser-boilerplate#6]
Hello,

Great boilerplate! 
Is browser-sync working? I can't see it being used anywhere.

Regards

**Comment by goldfire** [comment]
It should be, though it may need to be updated. It is setup in the Webpack config: https://github.com/goldfire/phaser-boilerplate/blob/master/build/webpack.config.js.

**Comment by MMrj9** [comment]
@goldfire  its working!
