### ISSUE TITLE
package.json issue

### ISSUE THREAD

**Issue by aronsuarez** [goldfire/phaser-boilerplate#7]
Hi 

Great work with this boilerplate

You has a small issue in the package.json.
By the exlude statment is the = missing.

`"dev:phaser": "cd node_modules/phaser-ce && npm i && grunt custom --exclude bitmaptext,retrofont,net,sound,ninja,p2,creature,video --split true",`

**Comment by goldfire** [comment]
Thanks! That has now been fixed.
