### ISSUE TITLE
problem with the phaser-boilerplate package

### ISSUE THREAD

**Issue by Daedric1012** [goldfire/phaser-boilerplate#8]
was having an issue merging this with my game so i tried to build just the straight-up basic package here and this is the resulting debug log and it just straight up fails to build.

my background is C# and Java so Javascript is very new to me and I am at a loss here.

[npm-debug.log](https://github.com/goldfire/phaser-boilerplate/files/1351180/npm-debug.log)

**Comment by goldfire** [comment]
Thanks! That has now been fixed.
