### ISSUE TITLE
Is there a purpose for /server.js?

### ISSUE THREAD

**Issue by rcdlopez** [goldfire/phaser-boilerplate#9]
I notice on **npm run dev:server** you're calling server.js with a port number of 7788. But server.js doesn't appear to do anything but log **Game server started at ${host} [${env}].**.

Is there a reason for this?

**Comment by goldfire** [comment]
If your game doesn't use a server then you can just get rid of it. Our games are multiplayer using a node server, so we included the basic server.js file as part of the template.
